version: '3.7'
services:
  eureka:
    container_name: eureka
    build:
      context: C:\Users\anusi\git\microservice1\eurekaserver
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    container_name: gateway
    build:
      context: C:\Users\anusi\git\microservice1\gateway
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      
  user:
    container_name: user
    build:
      context: C:\Users\anusi\git\microservice1\user
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      
  product:
    container_name: product
    build:
      context: C:\Users\anusi\git\microservice1\product
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
